### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by athornfam2** [sgjava/install-zabbix#2]
After a fresh install and new run of the script I'm receiving this error

./install.sh: 157: cannot open schema.sql: No such file
./install.sh: 158: cannot open images.sql: No such file
./install.sh: 159: cannot open data.sql: No such file

**Comment by athornfam2** [comment]
Forked and fixed in my own repo

**Comment by sgjava** [comment]
I just installed Zabbix 6.4.9 on fresh Ubuntu 22.04 VM and had no such issue. This must have been something in your local env.
